"""inventory_condition"""
from alembic import op
import sqlalchemy as sa

revision = 'fe28211ed699'
down_revision = '9a14c5c2f631'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('condition', sa.String(), server_default='good', nullable=False))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'condition')
    # ### end Alembic commands ###

