import {test,expect} from '@playwright/test'

test('BMW intake, approval review and mock publication',async({page})=>{
  await page.goto('/')
  await expect(page.getByText('System connected')).toBeVisible()
  await page.getByRole('button',{name:'Run task',exact:true}).click()
  await expect(page.getByRole('heading',{name:'BMW Alternator',exact:true})).toBeVisible()
  await expect(page.getByText('Listing draft ready')).toBeVisible()
  await expect(page.getByText('generate_listing_draft',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:/Review approval/}).click()
  const dialog=page.getByRole('dialog')
  await expect(dialog.getByRole('heading',{name:'Review business action'})).toBeVisible()
  await expect(dialog.getByText('Review duplicate candidates before publishing')).toBeVisible()
  await dialog.getByRole('button',{name:'Approve and execute'}).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByText(/Published to mock marketplace · MOCK-/)).toBeVisible()
  await page.screenshot({path:'../docs/screenshots/workspace.png',fullPage:true})
})

test('inventory filtering and order review',async({page})=>{
  await page.goto('/')
  await page.getByRole('button',{name:'Parts inventory',exact:true}).click()
  await page.getByRole('combobox',{name:'Brand filter'}).selectOption('Toyota')
  await page.getByRole('textbox',{name:'Search inventory'}).fill('DEMO-TOYOTA-MIR-001')
  await expect(page.getByRole('row').filter({hasText:'Toyota Mirror'})).toHaveCount(1)
  await page.getByRole('button',{name:'Orders',exact:true}).click()
  await page.getByRole('button',{name:'Prepare',disabled:false}).first().click()
  await expect(page.getByText('Human approval required before execution')).toBeVisible()
  await page.getByRole('button',{name:/Review approval/}).click()
  await page.getByRole('dialog').getByRole('button',{name:'Reject'}).click()
  await expect(page.getByRole('status')).toContainText('rejected')
})

test('ambiguous part asks for OEM, mobile layout stays usable',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await page.getByRole('textbox',{name:'Task description'}).fill('Process BMW alternator')
  await page.getByRole('button',{name:'Run task',exact:true}).click()
  await expect(page.getByText('Provide the exact details and run again.')).toBeVisible()
  await expect(page.getByRole('button',{name:/BMW Alternator · DEMO-BMW-ALT-001/})).toBeVisible()
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)
  expect(overflow).toBe(false)
  await page.screenshot({path:'../docs/screenshots/mobile.png',fullPage:true})
})
